# Generated by Django 5.2 on 2025-04-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='freelancers/')),
                ('category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Caretaker', 'Caretaker'), ('Handyman', 'Handyman'), ('movers', 'movers')], max_length=50)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='freelancers/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.freelancer')),
            ],
        ),
    ]
