# Generated by Django 5.2.1 on 2025-05-22 08:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='freelancers.freelancer'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='category',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Caretaker', 'Caretaker'), ('Handyman', 'Handyman'), ('Movers', 'Movers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
