# Generated by Django 5.2 on 2025-04-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='freelancers/videos/'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
