# Generated by Django 5.2 on 2025-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantroom',
            name='video_tour',
            field=models.FileField(blank=True, null=True, upload_to='vacancy_videos/'),
        ),
    ]
