# Generated by Django 5.1.7 on 2025-03-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_photos/'),
        ),
    ]
