# Generated by Django 5.2 on 2025-05-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vacantroom_video_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('help_text', models.TextField(verbose_name='How can we help?')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vacantroom',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Self-Contained', 'Self-Contained'), ('Bedsitter', 'Bedsitter'), ('Airbnb', 'Airbnb'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom'), ('4 Bedroom', '4 Bedroom')], max_length=20),
        ),
    ]
