# Generated by Django 5.2 on 2025-04-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_maintenancerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_rented',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property_address',
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='users.property'),
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
