# Generated by Django 5.2.1 on 2025-05-31 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_commercialproperty_picture1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Kitchen', 'Kitchen'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love')], max_length=10)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='users.item')),
            ],
            options={
                'unique_together': {('item', 'session_id', 'reaction_type')},
            },
        ),
    ]
