# Generated by Django 5.2 on 2025-04-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=100)),
                ('commercial_type', models.CharField(choices=[('Office', 'Office'), ('Retail', 'Retail'), ('Warehouse', 'Warehouse'), ('Industrial', 'Industrial')], max_length=30)),
                ('floor_space', models.DecimalField(decimal_places=2, help_text='In square meters', max_digits=10)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='commercial_images/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='commercial_images/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='commercial_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForSaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Land', 'Land'), ('Townhouse', 'Townhouse')], max_length=30)),
                ('lot_size', models.CharField(blank=True, max_length=50, null=True)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='sale_images/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='sale_images/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='sale_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
