# Generated by Django 5.1.7 on 2025-03-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tenant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='photo',
        ),
    ]
