# Generated by Django 5.2 on 2025-04-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
