# Generated by Django 5.2.1 on 2025-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_amenity_roomtype_bed_type_roomtype_view_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
