# Generated by Django 5.2.1 on 2025-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_reservation_room_reservation_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default='pending', max_length=20),
        ),
    ]
