# Generated by Django 5.2 on 2025-04-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Installment', 'Installment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(default='DEFAULT123', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='offplan.unit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='offplan.project'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='offplan.clientbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='offplan.project'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size_in_sqft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(max_length=50),
        ),
    ]
