# Generated by Django 5.2 on 2025-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offplan', '0002_remove_clientbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number_of_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
